name: go_bike
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # HTTP / Auth
  dio: ^4.0.4
  # State Management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.0.0
  equatable: ^2.0.2
  # Database / Security
  path_provider: ^2.0.9
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  # Animations / Display
  font_awesome_flutter: ^10.1.0
  lottie: ^1.2.1
  salomon_bottom_bar: ^3.3.1
  flutter_native_splash: ^2.2.7
  # Config
  dotenv: ^4.0.1
  # Location
  flutter_map: ^2.2.0
  latlong2: ^0.8.1
  geolocator: ^9.0.1
  flutter_map_location_marker: ^4.1.4
  mqtt_client: ^9.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - .env
    # Add assets from the images directory to the application.
    - assets/images/
