version: '3'

services:
  gobike-back:
    build:
      context: .
      dockerfile: Dockerfile
    # image: nodejs
    container_name: gobike-back
    restart: unless-stopped
    env_file: .env
    # environment:
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - gobike-network
    command: yarn dev

networks:
  gobike-network:
    driver: bridge

volumes:
  node_modules: